# Generated by Django 3.0.5 on 2020-09-30 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operating_countries', django_countries.fields.CountryField(blank=True, max_length=746, multiple=True)),
                ('account_status', models.CharField(default='free', max_length=7)),
                ('about_store', models.TextField(blank=True, default='optional', max_length=350, verbose_name='store-bio')),
                ('is_free', models.BooleanField(default=True, verbose_name='Account is free')),
                ('is_premium', models.BooleanField(default=False, verbose_name='Account is premium')),
                ('is_diamond', models.BooleanField(default=False, verbose_name='Account is Diamond')),
                ('store_payment_method', models.CharField(choices=[('POD', 'Buyer Pays On Point Of Delivery Only'), ('AMP', 'Buyer pays through our Admins with AfricaMarket simba only(buyer can be refunded if transaction is not fufilled)'), ('BTH', 'Payment on Delivery And through our Admins with AfricaMarket simba(buyer can be refunded if transaction is not fufilled)')], default='BTH', max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='ams_worth',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ams'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_number',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.CreateModel(
            name='ShelfFlags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre', models.BooleanField(default=False)),
                ('dia', models.BooleanField(default=False)),
                ('flags_owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.SellerProfile')),
            ],
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BuyerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=100, null=True, unique=True)),
                ('operating_countries', django_countries.fields.CountryField(max_length=746, multiple=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
