# Generated by Django 3.0.5 on 2020-09-30 16:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_auto_20200930_0931'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShelfTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelf_name', models.CharField(max_length=20)),
                ('image', models.ImageField(default='shelf_default.jpg', upload_to='shelf_profile_pics')),
                ('shelf_category', models.CharField(choices=[('None', 'None'), ('Electronics', 'Electronics'), ('Arts and Crafts', 'Arts and Crafts'), ('Native Attires', 'Native Attires'), ('Foreign Attire', 'Foreign Attire'), ('Indigenous Fashion Accesssories', 'Indigenous Fashion Accesssories'), ('Foreign Fashion Accesssories', 'Foreign Fashion Accesssories'), ('Make-ups', 'Make-ups'), ('Agricultural Produce', 'Agricultural Produce'), ('Building Materials', 'Building Materials'), ('Vehicles', 'Vehicles'), ('Cosmetics', 'Cosmetics'), ('Services', 'Services'), ('Bookstores', 'Bookstores'), ('Automobiles', 'Automobiles'), ('Interiors', 'Interiors'), ('Hardware Store', 'Hardware Store'), ('Hotels', 'Hotels'), ('Cooking Utensils', 'Cooking Utensils')], default='NONE', max_length=50)),
                ('shelf_size', models.IntegerField(default=75, editable=False)),
                ('slug', models.SlugField(default='', editable=False, max_length=1000)),
                ('shelf_owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.SellerProfile')),
            ],
        ),
        migrations.CreateModel(
            name='ShelfThree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelf_name', models.CharField(max_length=20)),
                ('image', models.ImageField(default='shelf_default.jpg', upload_to='shelf_profile_pics')),
                ('shelf_category', models.CharField(choices=[('None', 'None'), ('Electronics', 'Electronics'), ('Arts and Crafts', 'Arts and Crafts'), ('Native Attires', 'Native Attires'), ('Foreign Attire', 'Foreign Attire'), ('Indigenous Fashion Accesssories', 'Indigenous Fashion Accesssories'), ('Foreign Fashion Accesssories', 'Foreign Fashion Accesssories'), ('Make-ups', 'Make-ups'), ('Agricultural Produce', 'Agricultural Produce'), ('Building Materials', 'Building Materials'), ('Vehicles', 'Vehicles'), ('Cosmetics', 'Cosmetics'), ('Services', 'Services'), ('Bookstores', 'Bookstores'), ('Automobiles', 'Automobiles'), ('Interiors', 'Interiors'), ('Hardware Store', 'Hardware Store'), ('Hotels', 'Hotels'), ('Cooking Utensils', 'Cooking Utensils')], default='NONE', max_length=50)),
                ('shelf_size', models.IntegerField(default=75, editable=False)),
                ('slug', models.SlugField(default='', editable=False, max_length=1000)),
                ('shelf_owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.SellerProfile')),
            ],
        ),
        migrations.CreateModel(
            name='ShelfOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelf_name', models.CharField(max_length=20)),
                ('image', models.ImageField(default='shelf_default.jpg', upload_to='shelf_profile_pics')),
                ('shelf_category', models.CharField(choices=[('None', 'None'), ('Electronics', 'Electronics'), ('Arts and Crafts', 'Arts and Crafts'), ('Native Attires', 'Native Attires'), ('Foreign Attire', 'Foreign Attire'), ('Indigenous Fashion Accesssories', 'Indigenous Fashion Accesssories'), ('Foreign Fashion Accesssories', 'Foreign Fashion Accesssories'), ('Make-ups', 'Make-ups'), ('Agricultural Produce', 'Agricultural Produce'), ('Building Materials', 'Building Materials'), ('Vehicles', 'Vehicles'), ('Cosmetics', 'Cosmetics'), ('Services', 'Services'), ('Bookstores', 'Bookstores'), ('Automobiles', 'Automobiles'), ('Interiors', 'Interiors'), ('Hardware Store', 'Hardware Store'), ('Hotels', 'Hotels'), ('Cooking Utensils', 'Cooking Utensils')], default='NONE', max_length=50)),
                ('shelf_size', models.IntegerField(default=50, editable=False)),
                ('slug', models.SlugField(default='', editable=False, max_length=1000)),
                ('shelf_owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.SellerProfile')),
            ],
        ),
        migrations.CreateModel(
            name='ShelfFour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelf_name', models.CharField(max_length=20)),
                ('image', models.ImageField(default='shelf_default.jpg', upload_to='shelf_profile_pics')),
                ('shelf_category', models.CharField(choices=[('None', 'None'), ('Electronics', 'Electronics'), ('Arts and Crafts', 'Arts and Crafts'), ('Native Attires', 'Native Attires'), ('Foreign Attire', 'Foreign Attire'), ('Indigenous Fashion Accesssories', 'Indigenous Fashion Accesssories'), ('Foreign Fashion Accesssories', 'Foreign Fashion Accesssories'), ('Make-ups', 'Make-ups'), ('Agricultural Produce', 'Agricultural Produce'), ('Building Materials', 'Building Materials'), ('Vehicles', 'Vehicles'), ('Cosmetics', 'Cosmetics'), ('Services', 'Services'), ('Bookstores', 'Bookstores'), ('Automobiles', 'Automobiles'), ('Interiors', 'Interiors'), ('Hardware Store', 'Hardware Store'), ('Hotels', 'Hotels'), ('Cooking Utensils', 'Cooking Utensils')], default='NONE', max_length=50)),
                ('shelf_size', models.IntegerField(default=100, editable=False)),
                ('slug', models.SlugField(default='', editable=False, max_length=1000)),
                ('shelf_owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.SellerProfile')),
            ],
        ),
        migrations.CreateModel(
            name='ShelfFive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelf_name', models.CharField(max_length=20)),
                ('image', models.ImageField(default='shelf_default.jpg', upload_to='shelf_profile_pics')),
                ('shelf_category', models.CharField(choices=[('None', 'None'), ('Electronics', 'Electronics'), ('Arts and Crafts', 'Arts and Crafts'), ('Native Attires', 'Native Attires'), ('Foreign Attire', 'Foreign Attire'), ('Indigenous Fashion Accesssories', 'Indigenous Fashion Accesssories'), ('Foreign Fashion Accesssories', 'Foreign Fashion Accesssories'), ('Make-ups', 'Make-ups'), ('Agricultural Produce', 'Agricultural Produce'), ('Building Materials', 'Building Materials'), ('Vehicles', 'Vehicles'), ('Cosmetics', 'Cosmetics'), ('Services', 'Services'), ('Bookstores', 'Bookstores'), ('Automobiles', 'Automobiles'), ('Interiors', 'Interiors'), ('Hardware Store', 'Hardware Store'), ('Hotels', 'Hotels'), ('Cooking Utensils', 'Cooking Utensils')], default='NONE', max_length=50)),
                ('shelf_size', models.IntegerField(default=1000)),
                ('slug', models.SlugField(default='', editable=False, max_length=1000)),
                ('shelf_owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.SellerProfile')),
            ],
        ),
        migrations.CreateModel(
            name='ItemShelfTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='item_pics')),
                ('name', models.CharField(default='nameless', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('item_description', models.TextField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(choices=[('new', 'new'), ('best-seller', 'best-seller'), ('top-featured', 'top-featured')], max_length=15)),
                ('multiplier', models.DecimalField(decimal_places=2, default=0.5, editable=False, max_digits=3)),
                ('ams_value', models.DecimalField(decimal_places=2, editable=False, max_digits=1000)),
                ('date_posted', models.DateField(default=django.utils.timezone.now)),
                ('shelf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.ShelfTwo')),
            ],
        ),
        migrations.CreateModel(
            name='ItemShelfThree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='item_pics')),
                ('name', models.CharField(default='nameless', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('item_description', models.TextField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(choices=[('new', 'new'), ('best-seller', 'best-seller'), ('top-featured', 'top-featured')], max_length=15)),
                ('multiplier', models.DecimalField(decimal_places=2, default=0.5, editable=False, max_digits=3)),
                ('ams_value', models.DecimalField(decimal_places=2, editable=False, max_digits=1000)),
                ('date_posted', models.DateField(default=django.utils.timezone.now)),
                ('shelf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.ShelfThree')),
            ],
        ),
        migrations.CreateModel(
            name='ItemShelfOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='item_pics')),
                ('name', models.CharField(default='nameless', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('item_description', models.TextField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(choices=[('new', 'new'), ('best-seller', 'best-seller'), ('top-featured', 'top-featured')], max_length=15)),
                ('multiplier', models.DecimalField(decimal_places=2, default=0.5, editable=False, max_digits=3)),
                ('ams_value', models.DecimalField(decimal_places=2, editable=False, max_digits=1000)),
                ('date_posted', models.DateField(default=django.utils.timezone.now)),
                ('shelf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.ShelfOne')),
            ],
        ),
        migrations.CreateModel(
            name='ItemShelfFour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='item_pics')),
                ('name', models.CharField(default='nameless', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('dicount_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('item_description', models.TextField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(choices=[('new', 'new'), ('best-seller', 'best-seller'), ('top-featured', 'top-featured')], max_length=15)),
                ('multiplier', models.DecimalField(decimal_places=2, default=0.5, editable=False, max_digits=3)),
                ('ams_value', models.DecimalField(decimal_places=2, editable=False, max_digits=1000)),
                ('date_posted', models.DateField(default=django.utils.timezone.now)),
                ('shelf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.ShelfFour')),
            ],
        ),
        migrations.CreateModel(
            name='ItemShelfFive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='item_pics')),
                ('name', models.CharField(default='nameless', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('item_description', models.TextField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(choices=[('new', 'new'), ('best-seller', 'best-seller'), ('top-featured', 'top-featured')], max_length=15)),
                ('multiplier', models.DecimalField(decimal_places=2, default=0.5, editable=False, max_digits=3)),
                ('ams_value', models.DecimalField(decimal_places=2, editable=False, max_digits=1000)),
                ('date_posted', models.DateField(default=django.utils.timezone.now)),
                ('shelf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.ShelfFive')),
            ],
        ),
    ]
